# Generated by Django 3.2.3 on 2021-05-30 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to='product_pics')),
                ('name', models.CharField(max_length=255)),
                ('preview_text', models.TextField(max_length=200, verbose_name='Preview Text')),
                ('preview_details', models.TextField(max_length=1000, verbose_name='Preview Details')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app_shop.category')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
