# Generated by Django 3.2.3 on 2021-06-02 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orederitems',
            new_name='orderitems',
        ),
    ]
